name: Pull Request Verification

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "ci-check"
  cancel-in-progress: false

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    outputs:
      eslint_status: ${{ steps.eslint.outcome }}
      prettier_status: ${{ steps.prettier.outcome }}
      tests_status: ${{ steps.tests.outcome }}
      build_status: ${{ steps.build.outcome }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Check out repository code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: Set up Node.js
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      id: eslint
      continue-on-error: true
      run: npm run lint -ws --if-present

    - name: Run Prettier check
      id: prettier
      continue-on-error: true
      run: npm run prettier-check -ws --if-present

    - name: Run Tests
      id: tests
      continue-on-error: true
      run: npm run test -ws --if-present
      env:
        ATLASSIAN_SITE_URL: ${{ secrets.ATLASSIAN_SITE_URL }}
        ATLASSIAN_USERNAME: ${{ secrets.ATLASSIAN_USERNAME }}
        ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}

    - name: Run npm build
      id: build
      continue-on-error: true
      run: npm run build -ws --if-present

    - name: Report Errors
      if: ${{ always() }}
      run: |
        echo "ESLint status: ${{ steps.eslint.outcome }}"
        echo "Prettier status: ${{ steps.prettier.outcome }}"
        echo "Tests status: ${{ steps.tests.outcome }}"
        echo "Build status: ${{ steps.build.outcome }}"
        if [[ ${{ steps.eslint.outcome }} == 'failure' ]] \
        || [[ ${{ steps.prettier.outcome }} == 'failure' ]] \
        || [[ ${{ steps.tests.outcome }} == 'failure' ]] \
        || [[ ${{ steps.build.outcome }} == 'failure' ]]; then
          exit 1
        fi
